import jsPDF from "jspdf";

interface PdfOptions {
  title?: string;
  course?: string;
  date?: string;
  content: string;
  source: "study-helper" | "note-organizer" | "custom";
  /** If true, no watermark is added to the PDF */
  isPremium?: boolean;
}

// Colors
const BLUE = [37, 99, 235]; // primary
const DARK = [30, 41, 59];
const GRAY = [100, 116, 139];
const LIGHT_BLUE = [219, 234, 254];
const WHITE = [255, 255, 255];

function setColor(doc: jsPDF, rgb: number[]) {
  doc.setTextColor(rgb[0], rgb[1], rgb[2]);
}

function drawHeader(doc: jsPDF, opts: PdfOptions, pageWidth: number) {
  // Blue header bar
  doc.setFillColor(BLUE[0], BLUE[1], BLUE[2]);
  doc.rect(0, 0, pageWidth, 32, "F");

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  setColor(doc, WHITE);
  const title = opts.title || "Study Notes";
  doc.text(title, 14, 14);

  // Subtitle line
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  const parts: string[] = [];
  if (opts.course) parts.push(opts.course);
  if (opts.date) parts.push(opts.date);
  parts.push("Generated by Student Hub");
  doc.text(parts.join("  •  "), 14, 22);

  // Decorative line
  doc.setDrawColor(LIGHT_BLUE[0], LIGHT_BLUE[1], LIGHT_BLUE[2]);
  doc.setLineWidth(0.5);
  doc.line(14, 28, pageWidth - 14, 28);
}

function drawFooter(doc: jsPDF, pageWidth: number, pageHeight: number, pageNum: number) {
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  setColor(doc, GRAY);
  doc.text(`Page ${pageNum}`, pageWidth / 2, pageHeight - 8, { align: "center" });
  doc.text("Student Hub", 14, pageHeight - 8);
}

function drawWatermark(doc: jsPDF, pageWidth: number, pageHeight: number) {
  doc.saveGraphicsState();
  doc.setGState(new (doc as any).GState({ opacity: 0.06 }));
  doc.setFont("helvetica", "bold");
  doc.setFontSize(54);
  setColor(doc, GRAY);
  // Diagonal watermark across the page
  const centerX = pageWidth / 2;
  const centerY = pageHeight / 2;
  doc.text("StudyFlow Free", centerX, centerY, {
    align: "center",
    angle: 45,
  });
  doc.restoreGraphicsState();
}

function parseMarkdownLines(content: string): Array<{ type: "h2" | "h3" | "bullet" | "text" | "bold-text" | "empty"; text: string }> {
  const lines = content.split("\n");
  const parsed: Array<{ type: "h2" | "h3" | "bullet" | "text" | "bold-text" | "empty"; text: string }> = [];

  for (const raw of lines) {
    const line = raw.trimEnd();
    if (line.trim() === "") {
      parsed.push({ type: "empty", text: "" });
    } else if (line.startsWith("## ")) {
      parsed.push({ type: "h2", text: line.slice(3).replace(/\*\*/g, "") });
    } else if (line.startsWith("### ")) {
      parsed.push({ type: "h3", text: line.slice(4).replace(/\*\*/g, "") });
    } else if (line.startsWith("- ") || line.startsWith("• ") || /^\d+\.\s/.test(line)) {
      const bulletText = line.replace(/^[-•]\s/, "").replace(/^\d+\.\s/, "");
      parsed.push({ type: "bullet", text: bulletText.replace(/\*\*/g, "") });
    } else if (line.startsWith("**") && line.endsWith("**")) {
      parsed.push({ type: "bold-text", text: line.replace(/\*\*/g, "") });
    } else {
      parsed.push({ type: "text", text: line.replace(/\*\*/g, "") });
    }
  }
  return parsed;
}

export function generatePdf(opts: PdfOptions): void {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 14;
  const contentWidth = pageWidth - margin * 2;
  let y = 38;
  let pageNum = 1;

  drawHeader(doc, opts, pageWidth);

  const checkPageBreak = (needed: number) => {
    if (y + needed > pageHeight - 16) {
      drawFooter(doc, pageWidth, pageHeight, pageNum);
      doc.addPage();
      pageNum++;
      y = 14;
    }
  };

  const lines = parseMarkdownLines(opts.content);

  for (const line of lines) {
    switch (line.type) {
      case "empty":
        y += 3;
        break;

      case "h2":
        checkPageBreak(12);
        y += 4;
        // Section background
        doc.setFillColor(LIGHT_BLUE[0], LIGHT_BLUE[1], LIGHT_BLUE[2]);
        doc.roundedRect(margin - 2, y - 5, contentWidth + 4, 9, 1.5, 1.5, "F");
        doc.setFont("helvetica", "bold");
        doc.setFontSize(12);
        setColor(doc, BLUE);
        doc.text(line.text, margin, y);
        y += 8;
        break;

      case "h3":
        checkPageBreak(10);
        y += 2;
        doc.setFont("helvetica", "bold");
        doc.setFontSize(10);
        setColor(doc, DARK);
        doc.text(line.text, margin, y);
        y += 6;
        break;

      case "bullet": {
        doc.setFont("helvetica", "normal");
        doc.setFontSize(9.5);
        setColor(doc, DARK);
        const wrapped = doc.splitTextToSize(line.text, contentWidth - 8);
        checkPageBreak(wrapped.length * 4.5 + 2);
        // Bullet dot
        doc.setFillColor(BLUE[0], BLUE[1], BLUE[2]);
        doc.circle(margin + 2, y - 1, 0.8, "F");
        doc.text(wrapped, margin + 6, y);
        y += wrapped.length * 4.5 + 1.5;
        break;
      }

      case "bold-text":
        checkPageBreak(6);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(9.5);
        setColor(doc, DARK);
        const bWrapped = doc.splitTextToSize(line.text, contentWidth);
        doc.text(bWrapped, margin, y);
        y += bWrapped.length * 4.5 + 1;
        break;

      case "text":
      default: {
        doc.setFont("helvetica", "normal");
        doc.setFontSize(9.5);
        setColor(doc, DARK);
        const tWrapped = doc.splitTextToSize(line.text, contentWidth);
        checkPageBreak(tWrapped.length * 4.5 + 1);
        doc.text(tWrapped, margin, y);
        y += tWrapped.length * 4.5 + 1;
        break;
      }
    }
  }

  drawFooter(doc, pageWidth, pageHeight, pageNum);

  const fileName = (opts.title || "study-notes")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/-+$/, "");
  doc.save(`${fileName}.pdf`);
}
