project_id = "eyugxzdotdsqlcuqcgkc"

[functions.study-helper]
verify_jwt = false

[functions.note-organizer]
verify_jwt = false

[functions.revision-planner]
verify_jwt = false

[functions.flashcard-generator]
verify_jwt = false

[functions.pdf-summarizer]
verify_jwt = false

[functions.detect-subject]
verify_jwt = false

[functions.study-mode]
verify_jwt = false
