import { Share2, MessageCircle, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { toast } from "@/hooks/use-toast";
import { useState } from "react";
import jsPDF from "jspdf";

interface ShareResultButtonProps {
  text: string;
  title?: string;
  showWhatsApp?: boolean;
  className?: string;
}

const STUDYFLOW_LINK = "https://studyflowv.lovable.app";

const BLUE = [37, 99, 235];
const DARK = [30, 41, 59];
const GRAY = [100, 116, 139];
const LIGHT_BLUE = [219, 234, 254];
const WHITE = [255, 255, 255];

function buildSharePdf(title: string, content: string): Blob {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pw = doc.internal.pageSize.getWidth();
  const ph = doc.internal.pageSize.getHeight();
  const margin = 14;
  const cw = pw - margin * 2;
  let y = 38;
  let page = 1;

  // Header
  doc.setFillColor(BLUE[0], BLUE[1], BLUE[2]);
  doc.rect(0, 0, pw, 32, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(WHITE[0], WHITE[1], WHITE[2]);
  doc.text(title, margin, 14);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(`Generated by StudyFlow  •  ${STUDYFLOW_LINK}`, margin, 22);
  doc.setDrawColor(LIGHT_BLUE[0], LIGHT_BLUE[1], LIGHT_BLUE[2]);
  doc.setLineWidth(0.5);
  doc.line(margin, 28, pw - margin, 28);

  const footer = (p: number) => {
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(GRAY[0], GRAY[1], GRAY[2]);
    doc.text(`Page ${p}`, pw / 2, ph - 8, { align: "center" });
    doc.text("StudyFlow", margin, ph - 8);
  };

  const checkBreak = (needed: number) => {
    if (y + needed > ph - 16) {
      footer(page);
      doc.addPage();
      page++;
      y = 14;
    }
  };

  const lines = content.split("\n");
  for (const raw of lines) {
    const line = raw.trimEnd();
    if (line.trim() === "") { y += 3; continue; }

    if (line.startsWith("## ")) {
      checkBreak(12);
      y += 4;
      doc.setFillColor(LIGHT_BLUE[0], LIGHT_BLUE[1], LIGHT_BLUE[2]);
      doc.roundedRect(margin - 2, y - 5, cw + 4, 9, 1.5, 1.5, "F");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(12);
      doc.setTextColor(BLUE[0], BLUE[1], BLUE[2]);
      doc.text(line.slice(3).replace(/\*\*/g, ""), margin, y);
      y += 8;
    } else if (line.startsWith("### ")) {
      checkBreak(10);
      y += 2;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(DARK[0], DARK[1], DARK[2]);
      doc.text(line.slice(4).replace(/\*\*/g, ""), margin, y);
      y += 6;
    } else if (line.startsWith("- ") || line.startsWith("• ") || /^\d+\.\s/.test(line)) {
      const txt = line.replace(/^[-•]\s/, "").replace(/^\d+\.\s/, "").replace(/\*\*/g, "");
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9.5);
      doc.setTextColor(DARK[0], DARK[1], DARK[2]);
      const wrapped = doc.splitTextToSize(txt, cw - 8);
      checkBreak(wrapped.length * 4.5 + 2);
      doc.setFillColor(BLUE[0], BLUE[1], BLUE[2]);
      doc.circle(margin + 2, y - 1, 0.8, "F");
      doc.text(wrapped, margin + 6, y);
      y += wrapped.length * 4.5 + 1.5;
    } else {
      const txt = line.replace(/\*\*/g, "");
      const isBold = line.startsWith("**") && line.endsWith("**");
      doc.setFont("helvetica", isBold ? "bold" : "normal");
      doc.setFontSize(9.5);
      doc.setTextColor(DARK[0], DARK[1], DARK[2]);
      const wrapped = doc.splitTextToSize(txt, cw);
      checkBreak(wrapped.length * 4.5 + 1);
      doc.text(wrapped, margin, y);
      y += wrapped.length * 4.5 + 1;
    }
  }

  footer(page);

  return doc.output("blob");
}

const ShareResultButton = ({ text, title = "StudyFlow Result", showWhatsApp = true, className }: ShareResultButtonProps) => {
  const [sharing, setSharing] = useState(false);

  const handleShare = async () => {
    setSharing(true);
    try {
      const blob = buildSharePdf(title, text);
      const file = new File([blob], `${title.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}.pdf`, { type: "application/pdf" });

      if (navigator.share && navigator.canShare?.({ files: [file] })) {
        await navigator.share({
          title,
          text: `📚 ${title} — Generated with StudyFlow\n${STUDYFLOW_LINK}`,
          files: [file],
        });
        return;
      }

      // Fallback: download PDF
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = file.name;
      a.click();
      URL.revokeObjectURL(url);
      toast({ title: "PDF downloaded! Share it with friends 📄" });
    } catch (e: any) {
      if (e?.name !== "AbortError") {
        toast({ title: "Share failed", description: "PDF was downloaded instead.", variant: "destructive" });
      }
    } finally {
      setSharing(false);
    }
  };

  const handleWhatsApp = () => {
    const blob = buildSharePdf(title, text);
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${title.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}.pdf`;
    a.click();
    URL.revokeObjectURL(url);

    const msg = encodeURIComponent(`📚 ${title}\n\nGenerated with StudyFlow — ${STUDYFLOW_LINK}\n\nDownload the app and study smarter!`);
    window.open(`https://wa.me/?text=${msg}`, "_blank");
    toast({ title: "PDF downloaded! Share it on WhatsApp 💬" });
  };

  return (
    <div className={`flex gap-2 ${className || ""}`}>
      <Button variant="outline" size="sm" onClick={handleShare} disabled={sharing} className="gap-1.5 text-xs">
        {sharing ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Share2 className="h-3.5 w-3.5" />}
        Share PDF 🔥
      </Button>
      {showWhatsApp && (
        <Button variant="outline" size="sm" onClick={handleWhatsApp} className="gap-1.5 text-xs text-green-600 hover:text-green-700 border-green-200 hover:border-green-300 hover:bg-green-50 dark:text-green-400 dark:border-green-800 dark:hover:bg-green-900/30">
          <MessageCircle className="h-3.5 w-3.5" /> WhatsApp
        </Button>
      )}
    </div>
  );
};

export default ShareResultButton;
