// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-saved-outputs.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
function db(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_saved_outputs_default = defineTool({
  name: "list_saved_outputs",
  title: "List saved study outputs",
  description: "List the signed-in user's saved AI study outputs (summaries, notes, flashcards, exam questions, etc.), most recent first. Optionally filter by tool or subject.",
  inputSchema: {
    tool: z.string().optional().describe("Filter by tool name (e.g. 'study-helper', 'pdf-summarizer', 'flashcard-generator', 'practice-exam', 'note-organizer')."),
    subject: z.string().optional().describe("Filter by subject tag."),
    limit: z.number().int().min(1).max(50).optional().describe("Max rows to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ tool, subject, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = db(ctx).from("saved_outputs").select("id, tool, subject, custom_title, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (tool) q = q.eq("tool", tool);
    if (subject) q = q.eq("subject", subject);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-saved-output.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
function db2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_saved_output_default = defineTool2({
  name: "get_saved_output",
  title: "Get saved study output",
  description: "Fetch the full text and metadata of a single saved study output by id (must belong to the signed-in user).",
  inputSchema: {
    id: z2.string().uuid().describe("The saved output id.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await db2(ctx).from("saved_outputs").select("id, tool, subject, custom_title, output_text, input_data, created_at").eq("id", id).eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Not found" }], isError: true };
    return {
      content: [{ type: "text", text: data.output_text }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/tools/list-exam-sessions.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
function db3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_exam_sessions_default = defineTool3({
  name: "list_exam_sessions",
  title: "List practice exam sessions",
  description: "List the signed-in user's recent practice exam results, including score, weak/strong topics, and recommended focus areas.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).optional().describe("Max sessions to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await db3(ctx).from("exam_sessions").select("id, mode, score, total_questions, topics_weak, topics_strong, recommended_focus, time_used_seconds, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { sessions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/save-note.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
function db4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var save_note_default = defineTool4({
  name: "save_note",
  title: "Save a study note",
  description: "Save a note or summary into the signed-in user's StudyFlow Library so it appears alongside other study outputs.",
  inputSchema: {
    title: z4.string().min(1).describe("Short title for the note."),
    content: z4.string().min(1).describe("Markdown content of the note."),
    subject: z4.string().optional().describe("Optional subject tag.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, content, subject }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await db4(ctx).from("saved_outputs").insert({
      user_id: ctx.getUserId(),
      tool: "mcp-note",
      custom_title: title,
      subject: subject ?? null,
      output_text: content,
      input_data: { source: "mcp" }
    }).select("id, created_at").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Saved note ${data?.id}` }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "eyugxzdotdsqlcuqcgkc";
var mcp_default = defineMcp({
  name: "studyflow-mcp",
  title: "StudyFlow",
  version: "0.1.0",
  instructions: "Access the signed-in student's StudyFlow library and exam history. Use `list_saved_outputs` to browse saved summaries, notes, flashcards, and generated exams, `get_saved_output` to read one in full, `list_exam_sessions` to review recent practice exam scores and weak topics, and `save_note` to add a new note to the Library.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_saved_outputs_default, get_saved_output_default, list_exam_sessions_default, save_note_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
